In [1]:
# KMeans is an unsupervised ML algo
# it is called Kmeans because it  is the mean of x and y coordinates 

In [2]:
# we need to find the distance between every centroid(k) to see if it is a part of which cluster which makes it faster for low no of features but if no of features increases so does the time to calculate the dist 

In [ ]:
# calucating the accuracy of K means model is not that easy task

In [3]:
import numpy as np
import sklearn
from sklearn.preprocessing import scale
from sklearn.datasets import load_digits
from sklearn.cluster import KMeans
from sklearn import metrics

c:\users\sid\anaconda3\envs\tensor\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
digits=load_digits()

In [5]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [6]:
len(digits)

5

In [7]:
# scaling data down will save time for computation as it will lead to less outliers 
data=scale(digits.data)

In [8]:
data

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [11]:
y=digits.target

In [12]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [15]:
# to view the amount of classes in the labels
np.unique(y)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# to find the length of unique elements
len(np.unique(y))

10

In [17]:
# assigning the value of total length of possible outcomes to K, i.e. K=10 clusters are possible 
# data can be segregated into 10 clusters of digits which makes sense
k=len(np.unique(y))

In [18]:
k

10

In [20]:
# no of instances which we want to classify into clusters --> samples
# no of features that associates those instances
samples, features =data.shape

In [21]:
samples

1797

In [22]:
features

64

In [23]:
# scoring using sklearn module
def bench_k_means(estimator, name, data):
    estimator.fit(data)
    print('%-9s\t%i\t%.3f\t%.3f\t%.3f\t%.3f\t%.3f\t%.3f'
          % (name, estimator.inertia_,
             metrics.homogeneity_score(y, estimator.labels_),
             metrics.completeness_score(y, estimator.labels_),
             metrics.v_measure_score(y, estimator.labels_),
             metrics.adjusted_rand_score(y, estimator.labels_),
             metrics.adjusted_mutual_info_score(y,  estimator.labels_),
             metrics.silhouette_score(data, estimator.labels_,
                                      metric='euclidean')))

In [24]:
# KMeans Classifier 
clf=KMeans(n_clusters=k,init="random",n_init=10) # 
bench_k_means(clf,"1",data) # for "1" digit
# interia, 

1        	69599	0.583	0.628	0.605	0.452	0.601	0.136
